name: automerge

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
    outputs:
      changed:
        value: ${{ jobs.automerge.outputs.changed }}
      basesha:
        value: ${{ jobs.automerge.outputs.basesha }}

jobs:
  automerge:
    name: Automerge ${{ inputs.branch }}
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.rebase.outputs.changed }}
      basesha: ${{ steps.rebase.outputs.basesha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: topjohnwu/Magisk
          submodules: 'recursive'
          fetch-depth: 0

      - name: Setup git
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Add remote
        run: |
          git remote add other https://github.com/$GITHUB_REPOSITORY.git
          git fetch other

      - name: Rebase changes
        id: rebase
        run: |
          git checkout other/ci-management mergehelper.sh
          chmod +x mergehelper.sh
          ./mergehelper.sh ${{ inputs.branch }}
          rm -f mergehelper.sh

      - name: Remove workflows
        run: |
          git restore --staged .
          git rm -rf .github/workflows
          git commit -m "remove workflows"

      - name: Push result
        if: steps.rebase.outputs.changed == 'true'
        uses: ad-m/github-push-action@v0.8.0
        with:
          force: true
          branch: ci-build-${{ inputs.branch }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
