name: Lygisk CI

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: 
      - 'ci-management'
  workflow_dispatch:

concurrency: 
  group: lygisk-ci
  cancel-in-progress: false

jobs:
  automerge-stable:
    uses: programminghoch10/Lygisk/.github/workflows/automerge.yml@ci-management
    with:
      branch: stable
  automerge-beta:
    uses: programminghoch10/Lygisk/.github/workflows/automerge.yml@ci-management
    with:
      branch: beta
  automerge-canary:
    uses: programminghoch10/Lygisk/.github/workflows/automerge.yml@ci-management
    with:
      branch: canary
  automerge-madness:
    uses: programminghoch10/Lygisk/.github/workflows/automerge.yml@ci-management
    with:
      branch: madness
  build-stable:
    needs: automerge-stable
    uses: programminghoch10/Lygisk/.github/workflows/build.yml@ci-management
    with:
      branch: stable
  build-beta:
    needs: automerge-beta
    uses: programminghoch10/Lygisk/.github/workflows/build.yml@ci-management
    with:
      branch: beta
  build-canary:
    needs: automerge-canary
    uses: programminghoch10/Lygisk/.github/workflows/build.yml@ci-management
    with:
      branch: canary
  build-madness:
    needs: automerge-madness
    uses: programminghoch10/Lygisk/.github/workflows/build.yml@ci-management
    with:
      branch: madness
  deploy:
    if: always()
    needs: [build-stable, build-beta, build-canary, build-madness]
    uses: programminghoch10/Lygisk/.github/workflows/deploy.yml@ci-management
    secrets:
      KEYSTORE: ${{ secrets.KEYSTORE }}
      KEYSTORE_KEY: ${{ secrets.KEYSTORE_KEY }}
